dist: xenial
language: python
python:
  - 3.7
#  - 3.8-dev

sudo: required
# container based image (sudo: false) stopped working for some reason. Crashing the test script on database commit!

services:
  - docker
  - postgresql

cache: pip

install:
  - sudo apt-get install gcc
  - pip install 'pip>=8.1.2'
  - pip install pip-tools
  - pip install appdirs
before_script:
  # - psql -c "CREATE DATABASE test_tackle;" -U postgres
  # - psql -c "CREATE USER tackle WITH PASSWORD 'tackle';" -U postgres
  - make requirements
  - make deps
script:
  - make check
  - make test
# after_success:
# after_success:
