dist: xenial
language: python
python:
  - 3.7
#  - 3.8-dev

sudo: required
# container based image (sudo: false) stopped working for some reason. Crashing the test script on database commit!

services:
  - docker
  - postgresql

cache: pip
env:
  global:
    - secure: "yKPCUnXnJrmqbchMVki6IRqVeaLa9RPs4ty/8+UEYERGK1q6dkFtrfnVzzJFL8PeWMz0D+uoM8Xokrhzyowf8VsRluJwf+JOlNULwEhx8d2A8R3OqD16ecLb35MOhcIYh/bzLm4daLVP5sQXe8jjgNNGvSCNmzskcEAdDM/Ud+JBmpdDs9V6v+79bNHBYEz+pf5pzmvVFuY3ZM70/45gJ/wcmf0IUAEoy0mq2rDOj0Y1lrjuPJQ0vPMls+P1Utl2Nscvf/DJ3LD0Uyg84otV3Ieb7JMOf2OQIIDCk65QkTUmqju+d1mnEBXn/Oa4SoOwNxEWhOha5tEnQvkcdPaJRIQD0dKbvscQdOhMh7NA3CQqnws2TYwMmcU221gCMaSapcnHVYacMFXR2zMdH/QIv+mmJx/0SQh0KIiYhypyr73IFFzfl+dzD6NoN7ZadZ222NlSF0ImiP2aw8J/k1AoNk7eYU+XJoeJyP9Kd9mpb4HiyCHss8G/Ct0kiNT3UtbRWfmRghrXACByozYghmQM0qeKMZJcu5c9qXXxE/Q9hK2FL4qp9u+LNRPhJpaFBvMh1ZZnX08Qlkd15nO+CSlV2TVqHPhhYRKq69Jt0O1gWV+ah45Lblri+b+UZtB9ufC8ISevjDV1gCS6e3uKlbdluXxDql+sCvtlFNvzBpUIsgY=" #DOCKER_USER
    - secure: "engz5NoD1p4L/r2PP31xF+IHR0cDOdf12iPMl5PLmztFjxMKRPXaBzduEuvs05nf1QBcejt1IvUbTgWE5SJDW1t8Ck/q2U2z8rtXYiDIgd9HHOqfPkYSko/UoBIUt2gghL9xHPUFnmdo+3hU14AGzj6eThPvoFkY21abvaETIDebHjnxKLbciX+4HOBejQLcSBF4L5lBBnSdo0/BfAiUJkxfNbCpi4YCWtBq9nglGxnMHN5HoXGvdWpxN1Q/gy9IbSVxEe3xSMVuJ8bAlbQu7gzDWp7iFinJ+0TSXUStx4nGsDB/l85Ds2q3IMMz5w2fFW8l9mIbEi0N6tDZH5IcwnCK8ltEZO3OWVow/W9Jg87zr48CG7Y096r/dPLhnJC2+SH5J9cTAsyMGwrZk0cJppcimGE+ssffRDaySDUWwxaCPhyooMI4EX7wu1EdH8+LJG6LfLgAIIKxXMqMRwRWlQ3fAS9/QP+rY99Ex8B3S/PMwyK1BDKE9hb+zo/JlLuP+4CrEINvy+rwXXSNXUgSL+0DUl5SDr/8YNytDDovHOG1lk7dszTmKtK++LA/StNzQoSmtar2lONOcmFWn4Ne4GKDOJ7VlmhAdx+jgvRgG18hQg5SA3X+epjR7seZDqYsS2r7dJRAEtD1P1YktIdJgvHWnRmaourNmn3jnraH1wQ=" #DOCKER_PASS
install:
  - sudo apt-get install gcc
  - pip install 'pip>=8.1.2'
  - pip install pip-tools
  - pip install appdirs
before_script:
  # - psql -c "CREATE DATABASE test_tackle;" -U postgres
  # - psql -c "CREATE USER tackle WITH PASSWORD 'tackle';" -U postgres
  - make requirements
  - make deps
script:
  - make check
  - make test
# after_success:
# after_success:
